### ISSUE TITLE
Meta issue about the meta repo for meta discussions about the c# server

### ISSUE THREAD

**Issue by Perksey** [discord-csharp/meta#16]
This repo seems to have gone radio silent.

Is this still the preferred place for meta discussions or has that reverted to the meta channel?

If so, what will become of this repo? Will it be archived?

**Comment by JakenVeina** [comment]
Maybe there just haven't been any meta discussions to be had?

**Comment by Perksey** [comment]
I can think of a fair few, like the whole logo debate for instance. That would've been a lot cleaner in a GitHub issue

**Comment by patrickklaeren** [comment]
To be honest there hasn't been much to discuss and people don't seem to be very interested in taking things to GitHub with the exception of a couple of associates. I've lacked actually maintaining this because reasons - there isn't much of an excuse, other than there not being any immediate need for attention here since it has been quiet.

I'd like to think this still has a place - if we open up discussions instead of issues.

I'll action that now - I'll close this for the time being, if there's anything else we can reopen.
