### ISSUE TITLE
Consider renaming the #gui channel.

### ISSUE THREAD

**Issue by hizamakura** [discord-csharp/meta#8]
## Introduction
The `#gui` channel is often ignored or completely unseen, due to its name. Most WPF/MVVM questions go in the `#beginner` channels, even though it should be in `#gui` for the most part.

WinForms questions never appear in `#gui` either, it is purely in the beginner channels, unless it's something really advanced. So I feel like the `#gui` channel is misused.

## Rename the `#gui` channel to `#wpf`
Yes, I know that Xamarin, UWP and even WinForms can be discussed in the channel, and it even says so in the channel description. But it's rarely used for that, it's almost exclusively used for WPF questions. So I feel like naming it as so is appropriate.
If it does happen, I think we can still allow that kind of talk there, it's just that the channel needs more exposure, especially towards new people to the server who want to ask questions regarding WPF or MVVM.

### 1. The channel doesn't talk much about other frameworks.
> Out of [144,399 messages](https://chito.ge/9ycqUH4.png) so far, there has only been [320](https://chito.ge/5Bxxsr6.png) `Xamarin` mentions in the channel, and [1,648](https://chito.ge/9nJJhZ3.png) mentions of `WinForms`. Compare that to [6,485](https://chito.ge/7nNR2ZZ.png) mentions of `WPF`, you start to see the disparity of having it being named differently just to able to include other frameworks.

In fact, `WinForms` has been mentioned [4,276](https://chito.ge/6KsStzk.png) + [3,757](https://chito.ge/637VxZN.png) times in the `#beginner-0`  and `#general-csharp` channel, which makes it the much more preferred place to ask.

### 2. It allows for questions to be more organized.
It is known that questions that fit in their correct category should be asked in there, But this is more of a guideline and is a bit lax. That's why WinForms is allowed to be talked in the beginner channels.
But you never see any talk of WPF happening in there, apart from new members who haven't seen the `#gui` channel and what it is for. This change will make them notice it, and in turn, ask there instead.

### 3. The people who know about WPF generally tend to be in `#gui`.
The people who I know has always been able to answer my hard questions about WPF, always had been in that channel, whenever I accidentally asked in the beginner channels, or even in the general channel, it gets buried because no one can answer it.

After all, reading XAML + ViewModel code takes awhile, which makes people not want to read anything about it. The `#gui` channel is slower compared to the other channels, which increases the visibility and the chance of your question to be answered.

## Future channels
I don't think discussions of Xamarin and/or UWP isn't prevalent enough to warrant a separate channel for them, much less their own category. I think it should remain as is and but with just a channel rename to what they're primarily used for.

**Comment by Jay-Madden** [comment]
We could also consider a GUI category with #wpf #winforms and #otherfx or something. If we really wanna capture all GUI questions

**Comment by hizamakura** [comment]
I think #wpf and #winforms have enough people talking about them that it can warrant its own channel.

**Comment by Foxtrek64** [comment]
One concern I have is that this may send Xamarin and WinForms discussion into one of the beginner channels because those that do look for a channel for that won't find "gui" and will instead see "wpf" and assume that WinForms is off topic for that channel.

I could see having a dedicated WPF and WinForms channel, though it should probably be #wpf-and-uwp given the similarities of the language.

**Comment by Insire** [comment]
I actually like the channel the way it is. Due to the complexity of WPF and MVVM, discussions tend to be longer in this channel. I view the channel as sort of an advanced channel.

I'm prefer winforms questions to be in the beginner question channels, because beginners are the ones using that framework. And the quality of the questions reflect that.

Xamarin is covered by #mobile.

UWP and Avalonia dont generate many questions, so they can stay with #gui just fine and dont need their own channels.

**Comment by RubyNova** [comment]
I do not seeing this as being viable as a channel name. It will make `#gui/wpf` an outlier in our channel setup. If you want a new name, I advise picking something that is still a catch-all, because by this logic `#game-dev` should be renamed to `#unity`, because it is in a similar situation with Unity questions as opposed to the amount of questions other C# game dev technologies get.

> We could also consider a GUI category with #wpf #winforms and #otherfx or something. If we really wanna capture all GUI questions

Uniformity would become an issue here. If you did it for one category, I feel you'd have to do it for all of them or it will look out of place/weird. Inconsistent UX is not ideal.

I get Roslyn has its own channel, and perhaps you feel WPF should also be an exception, but I dislike that fact and the only reason its still around is because of the pushback on removing it.

**Comment by Pyrobolser** [comment]
I like the `#gui` channel as it is.
I do not think people ask their `#gui` question in the `#beginner` or `#general-csharp` because they cannot find the `#wpf` channel. We have a lot of beginners asking all kind of questions (database, asp.net, winforms, wpf, uwp) in the main channels because that's the first batch of channels they see and they look the most like "question/help" channel.

Maybe we should redirect properly people to the `#gui` channel when a GUI related question is asked. But I feel like it's already the case. When somebody knows the answer or is available to help, they do so and if they cannot, they redirect to `#gui` to get more info.
  
In my opinion, it already acts as some kind of filter to move more advanced questions in `#gui`. And at the end of day, the goal for the person asking the question is to find some help. Then they come back, they learn a little bit more about the Discord and how the other channels operate.

**Comment by tannergooding** [comment]
Maybe calling it `#ui` or `#user-interface` would make it more immediately obvious.

While gui is a correct term, it's not one I see being used as often as just UI or UX anymore.

**Comment by hizamakura** [comment]
Would `#desktop` work as it fits against the `#mobile` channel?

**Comment by Foxtrek64** [comment]
`#desktop` could also unintentionally loop in console apps and maybe others.

**Comment by Inzanit** [comment]
I personally don't think this channel needs renaming - there hasn't been much confusion and it can be redirected to as required.

**Comment by Foxtrek64** [comment]
> 
> 
> I personally don't think this channel needs renaming - there hasn't been much confusion and it can be redirected to as required.

I'm partial to agree. WPF and WinForms questions are allowed in the Beginner Questions channels - that's what they're there for. If we need to, we can redirect them to the GUI channel (or away from WPF/WinForms if it's their absolute first time even seeing the term "C#"), but I see no issue with these catch-all channels being used for exactly that purpose.

**Comment by hizamakura** [comment]
Would `#desktop-ui` work better?

**Comment by Trinitek** [comment]
> 
> 
> Would `#desktop-ui` work better?

That would probably work fine, but I'm not sure this is a problem that needs solving.  Are people confused as to what the purpose of the channel is?  If it were catching HTML/CSS questions I would be more receptive, but it isn't.

**Comment by hizamakura** [comment]
It’s not that people are confused to what it is. It's that people aren't finding the channel that fit their question. The fact that people needs to be redirected in the first place is the first sign that the channel needs more exposure. 

The goal is to make the channel more noticed, and redirection means that there could be improvements still made on the name.

**Comment by Pyrobolser** [comment]
>The fact that people needs to be redirected in the first place is the first sign that the channel needs more exposure.  
  
I think it's more of a general question then. In your opinion, people should ask their UI related questions in `#gui` and not in the `C# DEVELOPMENT` channels. I never thought this was the case, I always thought those channels could be use for any kind of questions (even database or mobile related) and if in need of more help we could redirect people. I thought this was how things were supposed to work, maybe not?

**Comment by hizamakura** [comment]
I'm specifically talking about WPF/MVVM questions. These questions never get answered in the beginner channels.

**Comment by RubyNova** [comment]
Then use the beginner and general channels more, tbh. General, Beginner and Advanced questions cover anything that is on topic. I don't needlessly shunt the many game dev questions I answer in those channels for the same reason. Our UX has always been structured like this, and I see no reason to alter it at this present time.

**Comment by hizamakura** [comment]
Honestly I would agree to that, if only the WPF and MVVM questions were actually answered outside of the gui channel. Occasionally they do, at most they don't.

**Comment by RubyNova** [comment]
Then as I said, people who answer those questions should use the general channels more. Changing a name won't resolve it, people don't properly scan our channel list anyway.

This really comes down to the community to make it better as opposed to us changing a name and it fixing the problem (which I believe it won't). This is not the answer and still see no real reason of it being so.

Not saying this to put you or anyone else down, but changes like this affect our UX as a whole. UX changes come about when there is an actual issue with the UX, which there is not here, based on the premise of the problem. If we want the general channels to support UI questions more, then we should find a way to get people more involved with those channels if their lack of participation there is the problem.

**Comment by RubyNova** [comment]
It appears discussion here has come to a standstill. I am closing this ticket. Thank you for your suggestion. 😄
